/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as CentralRouteImport } from './routes/central'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CobrancaRouteImport } from './routes/cobranca'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as EsteiraRouteImport } from './routes/esteira'
import { Route as FabricaRouteImport } from './routes/fabrica'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LojistasRouteImport } from './routes/lojistas'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as VeiculosRouteImport } from './routes/veiculos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaRoute = CobrancaRouteImport.update({
  id: '/cobranca',
  path: '/cobranca',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EsteiraRoute = EsteiraRouteImport.update({
  id: '/esteira',
  path: '/esteira',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricaRoute = FabricaRouteImport.update({
  id: '/fabrica',
  path: '/fabrica',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistasRoute = LojistasRouteImport.update({
  id: '/lojistas',
  path: '/lojistas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/central': typeof CentralRoute
  '/clientes': typeof ClientesRoute
  '/cobranca': typeof CobrancaRoute
  '/documentos': typeof DocumentosRoute
  '/esteira': typeof EsteiraRoute
  '/fabrica': typeof FabricaRoute
  '/login': typeof LoginRoute
  '/lojistas': typeof LojistasRoute
  '/marketing': typeof MarketingRoute
  '/relatorios': typeof RelatoriosRoute
  '/veiculos': typeof VeiculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/central': typeof CentralRoute
  '/clientes': typeof ClientesRoute
  '/cobranca': typeof CobrancaRoute
  '/documentos': typeof DocumentosRoute
  '/esteira': typeof EsteiraRoute
  '/fabrica': typeof FabricaRoute
  '/login': typeof LoginRoute
  '/lojistas': typeof LojistasRoute
  '/marketing': typeof MarketingRoute
  '/relatorios': typeof RelatoriosRoute
  '/veiculos': typeof VeiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/central': typeof CentralRoute
  '/clientes': typeof ClientesRoute
  '/cobranca': typeof CobrancaRoute
  '/documentos': typeof DocumentosRoute
  '/esteira': typeof EsteiraRoute
  '/fabrica': typeof FabricaRoute
  '/login': typeof LoginRoute
  '/lojistas': typeof LojistasRoute
  '/marketing': typeof MarketingRoute
  '/relatorios': typeof RelatoriosRoute
  '/veiculos': typeof VeiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/central'
    | '/clientes'
    | '/cobranca'
    | '/documentos'
    | '/esteira'
    | '/fabrica'
    | '/login'
    | '/lojistas'
    | '/marketing'
    | '/relatorios'
    | '/veiculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/central'
    | '/clientes'
    | '/cobranca'
    | '/documentos'
    | '/esteira'
    | '/fabrica'
    | '/login'
    | '/lojistas'
    | '/marketing'
    | '/relatorios'
    | '/veiculos'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/central'
    | '/clientes'
    | '/cobranca'
    | '/documentos'
    | '/esteira'
    | '/fabrica'
    | '/login'
    | '/lojistas'
    | '/marketing'
    | '/relatorios'
    | '/veiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CentralRoute: typeof CentralRoute
  ClientesRoute: typeof ClientesRoute
  CobrancaRoute: typeof CobrancaRoute
  DocumentosRoute: typeof DocumentosRoute
  EsteiraRoute: typeof EsteiraRoute
  FabricaRoute: typeof FabricaRoute
  LoginRoute: typeof LoginRoute
  LojistasRoute: typeof LojistasRoute
  MarketingRoute: typeof MarketingRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VeiculosRoute: typeof VeiculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca': {
      id: '/cobranca'
      path: '/cobranca'
      fullPath: '/cobranca'
      preLoaderRoute: typeof CobrancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esteira': {
      id: '/esteira'
      path: '/esteira'
      fullPath: '/esteira'
      preLoaderRoute: typeof EsteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrica': {
      id: '/fabrica'
      path: '/fabrica'
      fullPath: '/fabrica'
      preLoaderRoute: typeof FabricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojistas': {
      id: '/lojistas'
      path: '/lojistas'
      fullPath: '/lojistas'
      preLoaderRoute: typeof LojistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  CentralRoute: CentralRoute,
  ClientesRoute: ClientesRoute,
  CobrancaRoute: CobrancaRoute,
  DocumentosRoute: DocumentosRoute,
  EsteiraRoute: EsteiraRoute,
  FabricaRoute: FabricaRoute,
  LoginRoute: LoginRoute,
  LojistasRoute: LojistasRoute,
  MarketingRoute: MarketingRoute,
  RelatoriosRoute: RelatoriosRoute,
  VeiculosRoute: VeiculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
