/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentralRouteImport } from './routes/central'
import { Route as EsteiraRouteImport } from './routes/esteira'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LojistasRouteImport } from './routes/lojistas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const EsteiraRoute = EsteiraRouteImport.update({
  id: '/esteira',
  path: '/esteira',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistasRoute = LojistasRouteImport.update({
  id: '/lojistas',
  path: '/lojistas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/central': typeof CentralRoute
  '/esteira': typeof EsteiraRoute
  '/login': typeof LoginRoute
  '/lojistas': typeof LojistasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/central': typeof CentralRoute
  '/esteira': typeof EsteiraRoute
  '/login': typeof LoginRoute
  '/lojistas': typeof LojistasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/central': typeof CentralRoute
  '/esteira': typeof EsteiraRoute
  '/login': typeof LoginRoute
  '/lojistas': typeof LojistasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/central' | '/esteira' | '/login' | '/lojistas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/central' | '/esteira' | '/login' | '/lojistas'
  id: '__root__' | '/' | '/central' | '/esteira' | '/login' | '/lojistas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentralRoute: typeof CentralRoute
  EsteiraRoute: typeof EsteiraRoute
  LoginRoute: typeof LoginRoute
  LojistasRoute: typeof LojistasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esteira': {
      id: '/esteira'
      path: '/esteira'
      fullPath: '/esteira'
      preLoaderRoute: typeof EsteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojistas': {
      id: '/lojistas'
      path: '/lojistas'
      fullPath: '/lojistas'
      preLoaderRoute: typeof LojistasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentralRoute: CentralRoute,
  EsteiraRoute: EsteiraRoute,
  LoginRoute: LoginRoute,
  LojistasRoute: LojistasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
